maxPotential = 1
plotUpdateTimeIntervall = 10
plotWaveFunctionAbsoluteFactor = 10000
plotWaveFunctionUpdateTimeFactor = 10
relativeInitialPointPosition = [0.25, 0.5]
relativeHolePosition = [0.75, 0.5]
relativeBallHoleDistanceConsideredAGoal = 0.1
velocityPrefactor = 1
initialNumberOfTries = 5